version: "3"
networks:
  jastie:

services:
  api:
    extends:
      file: "dev-compose.yaml"
      service: jastie-api
    entrypoint: "poetry run test"
    env_file: "test.env"

  postgres:
    extends:
      file: "dev-compose.yaml"
      service: jastie-postgres
    env_file: "test.env"


  redis:
    extends:
      file: "dev-compose.yaml"
      service: jastie-redis
