name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Tests
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          submodules: true

          file: test-compose.yaml
