name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_KEY }}
          submodules: true
      - name: Build
        run: "docker compose -f test-compose.yaml build"
      - name: Tests
        run: "docker compose -f test-compose.yaml up --exit-code-from api --attach api"