name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_KEY }}
          submodules: true

      - name: Tests
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "test-compose.yaml"
          up-flags: "--exit-code-from api"
