name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_KEY }}
          submodules: true

      - name: Tests
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: test-compose.yaml
          service: api
          command: "poetry run test"
